# .github/workflows/deploy.yml

name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Or whatever your default branch is

# Add this permissions block
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Create Firebase Config 🤫
        run: |
          sed -i "s|REPLACE_WITH_API_KEY|${{ secrets.FIREBASE_API_KEY }}|g" firebase-config.js
          sed -i "s|REPLACE_WITH_AUTH_DOMAIN|${{ secrets.FIREBASE_AUTH_DOMAIN }}|g" firebase-config.js
          sed -i "s|REPLACE_WITH_PROJECT_ID|${{ secrets.FIREBASE_PROJECT_ID }}|g" firebase-config.js
          sed -i "s|REPLACE_WITH_STORAGE_BUCKET|${{ secrets.FIREBASE_STORAGE_BUCKET }}|g" firebase-config.js
          sed -i "s|REPLACE_WITH_MESSAGING_SENDER_ID|${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}|g" firebase-config.js
          sed -i "s|REPLACE_WITH_APP_ID|${{ secrets.FIREBASE_APP_ID }}|g" firebase-config.js
          sed -i "s|REPLACE_WITH_MEASUREMENT_ID|${{ secrets.FIREBASE_MEASUREMENT_ID }}|g" firebase-config.js

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: . # The folder the action should deploy.
